# Generated by Django 3.0.7 on 2020-06-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_invitecodemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_update',
            field=models.BooleanField(default=True),
        ),
    ]
